<%-- 
    Document   : employee_head
    Created on : 20 Sep, 2012, 1:04:00 PM
    Author     : sivaraja
--%>

<%@page contentType="text/html" pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
    <head>
        <link href="../../css/menus/SpryMenuBarHorizontal.css" rel="stylesheet" type="text/css" />
        <link href="../../css/style.css" rel="stylesheet" type="text/css" />
    </head>
    <body>
        <table width="1000px" align="center" id="main_table">
            <tr>
                <td  width="1000px" id="main_header"> 
                    <!--Header start -->
                    <img src="../../images/logo1.gif" alt=""  ></img>
                    <table width="" align="right">
                        <tr >
                            <td class="welcome">Welcome to Mr.Raju</td>
                            <td ><a href="../index.jsp" id="out" />Logout</a></td>
                        </tr>
                    </table>
                    <!--header end -->							
                </td>					
            </tr>
            <tr>
                <td width="1000px"> 
                    <!--Menu start --> 
                    <!-- Deluxe Menu -->
                    <!-- Code for Deluxe Menu Items. Generated by Deluxe Tuner -->
                    <div id='cssmenu'>
                        <ul>
                            <li class='active '><a href='employee_home.jsp'><span>Home</span></a></li>
                            <li class='has-sub '><a href='#'><span>Search</span></a>
                                <ul>
                                    <li><a href='#'><span>Advanced Search</span></a></li>
                                    <li><a href='#'><span>Jobs By Function </span></a></li>
                                    <li><a href='#'><span>Jobs By Industry</span></a></li>
                                    <li><a href='#'><span>Jobs By Location</span></a></li>
                                    <li><a href='#'><span>Jobs By Company</span></a></li>
                                </ul>
                            </li>
                            <li><a href='#'><span>Submit Resume</span></a></li>
                            <li class='has-sub '><a href='#'><span>Account Settings</span></a>
                                <ul>
                                    <li><a href='employee_view_prof.jsp'><span>View Profile</span></a></li>
                                    <li><a href='change_password.jsp'><span>Change Passwrod</span></a></li>
                                </ul>
                            </li>

                            <li></li></ul>
                    </div>
                    <!--Menu end -->										
                </td>					
            </tr>
        </table>
    </body>
</html>
