<%-- 
    Document   : admin_head1
    Created on : 22 Sep, 2012, 1:32:39 PM
    Author     : ramu
--%>

<%-- 
    Document   : employer_head
    Created on : 20 Sep, 2012, 2:34:01 PM
    Author     : sivaraja
--%>

<%@page contentType="text/html" pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
    <head>
       <link href="../../css/menus/SpryMenuBarHorizontal.css" rel="stylesheet" type="text/css" />
       <link href="../../css/style.css" rel="stylesheet" type="text/css" />
    </head>
    <body>
        <table width="1000px" align="center" id="main_table">
					<tr>
							<td  width="1000px" id="main_header" > 
							<!--Header start -->
							<img src="../../images/logo1.gif" alt=""  ></img>
							<table width="" align="right">
								<tr>
								
								</tr>
							</table>
							<!--header end -->							
							</td>					
					</tr>
					<tr>
							<td width="1000px"> 
							<!--Menu start --> 
							<!-- Deluxe Menu -->
							<!-- Code for Deluxe Menu Items. Generated by Deluxe Tuner -->
							<div id='cssmenu'>
                                                                <ul>
   								<li class='active '><a href='#'><span></span></a></li>
   								<li><a href='#'><span></span></a></li>
   								<li><a href='#'><span></span></a></li>
   								<li ><a href='#'><span></span></a> </li>
   								 <li><a href='#'><span></span></a></li>
								</ul></div>
							<!--Menu end -->										
							  </td>					
					</tr>
        </table>
    </body>
</html>
