<%-- 
    Document   : admin_head
    Created on : 23 Sep, 2012, 2:06:01 PM
    Author     : sivaraja
--%>

<%@page contentType="text/html" pageEncoding="UTF-8"%>

<%@taglib uri="http://struts.apache.org/tags-bean" prefix="bean" %>
<!DOCTYPE html>
<html>
    <head>
        <link href="../../css/menus/SpryMenuBarHorizontal.css" rel="stylesheet" type="text/css" />
        <link href="../../css/style.css" rel="stylesheet" type="text/css" />
    </head>
    <body>
        <table width="1000px" align="center" id="main_table">
            <tr>
                <td  width="1000px" id="main_header" > 
                    <!--Header start -->
                    <img src="../../images/logo1.gif" alt=""  ></img>
                    <table width="" align="right">
                        <tr>
                            <td><strong>Welcome To Administrator</strong></td>
                            <td><a href="./logout.do?user='admin'">Logout</a></td>
                        </tr>
                        <tr><td>login-time:<bean:write name="adminvo" property="loginTime" scope="session"></bean:write></td></tr>
                    </table>
                    <!--header end -->							
                </td>					
            </tr>
            <tr>
                <td width="1000px"> 
                    <!--Menu start --> 
                    <!-- Deluxe Menu -->
                    <!-- Code for Deluxe Menu Items. Generated by Deluxe Tuner -->
                    <div id='cssmenu'>
                        <ul>
                            <li class='active '><a href='#'><span>HOME</span></a></li>
                            <li><a href='packagecreation.jsp'><span>Package Creation</span></a></li>
                            <li><a href='#'><span></span></a></li>
                            <li ><a href='#'><span></span></a> </li>
                            <li><a href='#'><span></span></a></li>
                        </ul></div>
                    <!--Menu end -->										
                </td>					
            </tr>
        </table>
    </body>
</html>

