<%-- 
    Document   : emp_reg_head
    Created on : 20 Sep, 2012, 1:53:46 PM
    Author     : sivaraja
--%>

<%@page contentType="text/html" pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
    <head>
        <link href="../../css/menus/SpryMenuBarHorizontal.css" rel="stylesheet" type="text/css" />
        <link href="../../css/style.css" rel="stylesheet" type="text/css" />
    </head>
    <body bgcolor="#E5E5E5">
        <table width="100%" >
            <tr>
                <td width="1000px" align="center" >
                    <table width="1000px" align="center" id="main_table">
                        <tr>
                            <td  width="1000px" id="main_header"> 
                                <!--Header starts here -->
                                <img src="../../images/logo1.gif" alt=""  ></img>
                                <table width="" align="right">
                                    <tr>
                                        <td ><a href="reg_createaccount.jsp" id="out">&nbsp;Register&nbsp;</a>|<a  href="employer_login.jsp" id="out">&nbsp;Login&nbsp;</a></td>
                                </table>
                                <!--header end  over-->							
                            </td>					
                        </tr>
                        <tr>
                            <td width="1000px"> 
                                <!--Menu sta --> 
                                <!-- Deluxe Menu -->
                                <!-- Code for Deluxe Menu Items. Generated by Deluxe Tuner -->
                                <div id='cssmenu'>
                                    <ul>
                                        <li class='active '><a href="../index.jsp"><span>Home</span></a></li>
                                        <li><a href='#'><span>Search</span></a>
                                            <ul>
                                                <li><a href='#'><span>Advanced Search</span></a></li>
                                                <li><a href='#'><span>Jobs By Function </span></a></li>
                                                <li><a href='#'><span>Jobs By Industry</span></a></li>
                                                <li><a href='#'><span>Jobs By Location</span></a></li>
                                                <li><a href='#'><span>Jobs By Company</span></a></li>
                                            </ul>   								
                                        </li>
                                        <li><a href='#'><span>Submit Resume</span></a></li>
                                        <li style="width:490px;">&nbsp;</li><li><a href='../employer/employer_login.jsp'><span>Employer's Zone</span></a></li>
                                    </ul>
                                </div>

                                <!--Menu end -->										
                            </td>					
                        </tr>
                    </table>
                </td></tr></table>
    <jsp:include page="employer_banner.jsp"></jsp:include>
    </body>
</html>


